baseURL = "/"
languageCode = "en-us"
title = "Microsoft Technical Skills"
theme = "hugo-theme-learn"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = "blue"
disableNextPrev = true

[[menu.shortcuts]] 
name = "<i class='fab fa-microsoft'></i> Microsoft Learn"
url = "https://docs.microsoft.com/en-us/learn/browse/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-link'></i> Link MS Learn Profile"
url = "http://aka.ms/mslearnaccountlinking"
weight = 11

[[menu.shortcuts]]
name = "<i class=\"fas fa-sync\"></i> Link MCP ID"
url = "https://support.microsoft.com/en-us/help/2966380/link-or-unlink-an-mcp-id-to-or-from-a-partner-organization"
weight = 12

[[menu.shortcuts]]
name = "<i class=\"fas fa-compass\"></i> CertComp Explorer"
url = "https://aka.ms/certcomp"
weight = 13